@startuml attestation
!include style.puml

skinparam BoxPadding 10

'title Nautilus Trusted Compute - Azure attestation flow

autonumber
actor "User" as user
box "Nautilus"
  participant "Service" as service
  participant "App Enclave" as appEnclave
end box
box "Azure"
  participant "Quoting Enclave" as quotingEnclave <<azure>>
  participant "Azure Attestation\nService" as azureAttestation <<azure>>
end box
user -> service: Request attestation
service -> quotingEnclave: Request target info
service <-- quotingEnclave: Return target info
service -> appEnclave: Request report with target info
service <-- appEnclave: Return report and public pey
service -> quotingEnclave: Request quote using report
service <-- quotingEnclave: Return quote
service -> azureAttestation: Verify quote with public key
service <-- azureAttestation: Return attestation token
user <-- service: Return attestation token
user -> azureAttestation: Request signing certificates
azureAttestation --> user: Return signing certificates
user -> user: Verify signature of attestion token
@enduml
