@startuml execute_drt_user_story
!include style.puml

skinparam BoxPadding 10

actor "Data Provider" as C
participant "Frontend Web App" as FWA
participant "Solana Smart Contract" as SC
participant "Trusted Execution Environment" as TEE
participant "Oracle Node" as ON
participant "Solana Blockchain" as SB

FWA -[#grey]-> TEE: <color:grey>a. (Optionally) Request TEE attestation</color>
TEE -[#grey]-> TEE: <color:grey>b. Perform attestation</color>
TEE -[#grey]-> FWA: <color:grey>c. Attestation result</color>

C -> FWA: 1. Submit purchase request for ExecuteDRT token(s) \n for a specific pool (e.g. ExecuteMedianDRT)
FWA -> SC: 2. Initiate ExecuteDRT transaction
activate SC
SC -> FWA: 3. Transaction executed successfully
deactivate SC


C -> FWA: 4. Select pool for ExecuteDRT operation and \n initialize DRT redemption
FWA -> SC: 5. Redeem ExecuteDRT using smart contract
activate SC
SC -> FWA: 6. ExecuteDRT redeemed successfully
deactivate SC

FWA -> TEE: 7. Request DRT execution for pool
TEE -> ON: 8. Request verification from Oracle Node(s)
ON <-> SB: 9. Qeury Solana and verify DRT redemption \n (e.g. median, mean, etc.)
ON -> TEE: 10. Return verification result
TEE -> TEE: 11. Unseal existing data, perform DRT operation \n (e.g. median, mean, etc.)
TEE -> FWA: 12. Transfer result over encrypted channel
FWA -> C: 12. ExecuteDRT operation result

@enduml