<style>
sequenceDiagram {
  box {
    LineColor #ffffff
    BackGroundColor #f1f1f6
  }
  arrow {
    LineColor #e6453f
  }
  lifeLine {
    LineColor #e6453f
  }

  actor {
    LineColor #003450
    BackGroundColor #fffff
  }

  database {
    LineColor #003450
    BackGroundColor #fffff
  }

  participant {
    LineColor #003450
    BackGroundColor #fffff
  }
  .azure {
    LineColor #28427b
  }
}
</style>

skinparam shadowing false
'skinparam classFontSize 10
