@startuml dataProvisioning via webApp
!include style.pum
skinparam dpi 300

title Nautilus Trusted Compute - Data Provisioning flow

box "Client Side"
  actor "Data Creator" as dataCreator
  participant "Vault App" as webApp
end box
participant "Data Service" as dataService
database "Data Storage" as storage

autonumber
dataCreator -> webApp: Request Attestation
webApp -> dataService: Request Attestation
...Attestation flow ommitted for brevity...
webApp <-- dataService: Return Attestation JWT
dataCreator <- webApp: Display Attestation Result

dataCreator -> webApp: Verify schema of data is valid \nfor pre-defined schemas
dataCreator <-- webApp: Data schema is valid

dataCreator -> webApp: Encrypt data with enclave key \nobtained from JWT
dataCreator -> webApp: Create sealed envelope with \nencrypted data, schema metadata \nand keys
webApp -> dataService: Upload sealed envelope
dataService -> storage: Save sealed envelope to storage

@enduml
